countryDescriptor createCountryDescriptor();
country *createCountry(char name[]);
void insertCountry(countryDescriptor &countries, char name[]);
country *getFirstCountry(countryDescriptor countries);
country *getLastCountry(countryDescriptor countries);
country *getFirstCountrySection(countryDescriptor countries);
country *getLastCountrySection(countryDescriptor countries);
country *getCurrentCountry(countryDescriptor countries);
country *getNextCountry(countryDescriptor countries);
country *getPreviousCountry(countryDescriptor countries);
void moveToNextCountry(countryDescriptor &countries);
void moveToPreviousCountry(countryDescriptor &countries);
void moveToFirstCountry(countryDescriptor &countries);
void moveToFirstCountrySection(countryDescriptor &countries);
void moveToLastCountry(countryDescriptor &countries);
void moveToLastCountrySection(countryDescriptor &countries);
int isCountryTheLast(countryDescriptor countries);
int isCountryTheFirst(countryDescriptor countries);
int isEndOfCountries(countryDescriptor countries);
int isEndOfCountriesSection(countryDescriptor countries);
int isCountriesEmpty(countryDescriptor countries);
country *getCountryByNode(countryDescriptor countries, int nodes);
country *getCountryByNodeInSection(countryDescriptor countries, int nodes);
void getCountriesFirstLetters(countryDescriptor countries, char letters[], int &size);
void getCountriesFromFirstLetter(countryDescriptor &countries, char letter);
void removeCountry(countryDescriptor &countries, country *toRemove);